name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install -U pip && pip install -r collector/requirements.txt
      - name: Validate JSON
        run: . .venv/bin/activate && python collector/validate.py
