name: Deploy DCC Archive to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'tools/build_index.py'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build index
        run: |
          python tools/build_index.py || true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./data
  deploy:
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
